<a href="https://colab.research.google.com/github/Adiatmaja/kedaireka/blob/main/LocalBinaryPattern.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cv2
import os

folder = os.listdir('gambar')
files = []
for i in folder:
  image = cv2.imread(i)
  files.append(image)
  image

FileNotFoundError: ignored

In [ ]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
   
      
def get_pixel(img, center, x, y):
      
    new_value = 0
      
    try:
        # If local neighbourhood pixel 
        # value is greater than or equal
        # to center pixel values then 
        # set it to 1
        if img[x][y] >= center:
            new_value = 1
              
    except:
        # Exception is required when 
        # neighbourhood value of a center
        # pixel value is null i.e. values
        # present at boundaries.
        pass
      
    return new_value
   
# Function for calculating LBP
def lbp_calculated_pixel(img, x, y):
   
    center = img[x][y]
   
    val_ar = []
      
    # top_left
    val_ar.append(get_pixel(img, center, x-1, y-1))
      
    # top
    val_ar.append(get_pixel(img, center, x-1, y))
      
    # top_right
    val_ar.append(get_pixel(img, center, x-1, y + 1))
      
    # right
    val_ar.append(get_pixel(img, center, x, y + 1))
      
    # bottom_right
    val_ar.append(get_pixel(img, center, x + 1, y + 1))
      
    # bottom
    val_ar.append(get_pixel(img, center, x + 1, y))
      
    # bottom_left
    val_ar.append(get_pixel(img, center, x + 1, y-1))
      
    # left
    val_ar.append(get_pixel(img, center, x, y-1))
       
    # Now, we need to convert binary
    # values to decimal
    power_val = [1, 2, 4, 8, 16, 32, 64, 128]
   
    val = 0
      
    for i in range(len(val_ar)):
        val += val_ar[i] * power_val[i]
          
    return val
   
path = 'gambarrrr.png'
img_bgr = cv2.imread(path, 1)
   
height, width, _ = img_bgr.shape
   
# We need to convert RGB image 
# into gray one because gray 
# image has one channel only.
img_gray = cv2.cvtColor(img_bgr,
                        cv2.COLOR_BGR2GRAY)
   
# Create a numpy array as 
# the same height and width 
# of RGB image
img_lbp = np.zeros((height, width),
                   np.uint8)
   
for i in range(0, height):
    for j in range(0, width):
        img_lbp[i, j] = lbp_calculated_pixel(img_gray, i, j)
  
plt.imshow(img_bgr)
plt.show()
   
plt.imshow(img_lbp, cmap ="gray")
plt.show()
   
print("LBP Program is finished")

AttributeError: ignored

In [ ]:
# import required module
import glob
import cv2
 
# get the path/directory
folder_dir = 'gambar'

i = 0
 
# iterate over files in
# that directory
for images in glob.iglob(f'{folder_dir}/*'):
   
    # check if the image ends with png
    if (images.endswith(".png")):
      hasil1  = cv2.imread(images)
      print(hasil1)

gambar/gambar_6.png
gambar/gambar_2.png
gambar/gambar_1.png
gambar/gambar_4.png
gambar/gambar_5.png
gambar/gambar_3.png
gambar/gambar_6.png
gambar/gambar_2.png
gambar/gambar_1.png
gambar/gambar_4.png
gambar/gambar_5.png
gambar/gambar_3.png


In [ ]:

import cv2
image = cv2.imread("ss.png")
  
# Now, the variable 'image' stores the pixel values of image
print(image)

[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [43 43 43]
  [43 43 43]
  [43 43 43]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[53 41 30]
  [53 41 30]
  [53 41 30]
  ...
  [15 15 15]
  [15 15 15]
  [15 15 15]]

 [[53 41 30]
  [53 41 30]
  [53 41 30]
  ...
  [15 15 15]
  [15 15 15]
  [15 15 15]]

 [[53 41 30]
  [53 41 30]
  [53 41 30]
  ...
  [15 15 15]
  [15 15 15]
  [15 15 15]]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')